name: meme_generator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.3" # Dart SDK version
  flutter: 3.16.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.2.0
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  mobx: ^2.3.0+1
  get_it: ^7.6.7
  cached_network_image: ^3.3.1
  flutter_mobx: ^2.2.0+2
  photo_view: ^0.14.0
  http: ^1.2.0
  flutter_native_splash: ^2.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/image/logo_to_surf_proj.png
    